Move the content of the bash script under run section to see why it don't work. #kaniko

diff --git a/.github/workflows/e2e-buildah-k8s.yml b/.github/workflows/e2e-buildah-k8s.yml
--- a/.github/workflows/e2e-buildah-k8s.yml
+++ b/.github/workflows/e2e-buildah-k8s.yml
@@ -52,7 +52,31 @@ jobs:
 
       - name: "Wait till job's finished and check status: complete or failed"
         working-directory: buildah
-        run: ./hack/check_job_status.sh
+        # ./hack/check_job_status.sh
+        run: |
+          while true; do
+            if kubectl -n buildpack wait --timeout=300s --for=condition=complete job/kaniko-poc 2>/dev/null; then
+              job_result=0
+              break
+            fi
+
+            if kubectl -n buildpack wait --timeout=300s --for=condition=failed job/kaniko-poc 2>/dev/null; then
+              job_result=1
+              break
+            fi
+
+            kubectl -n buildpack get job/kaniko-poc -o yaml
+
+            sleep 3
+          done
+
+          if [[ $job_result -eq 1 ]]; then
+            echo "Job failed!"
+            exit 1
+          fi
+
+          echo "Job succeeded"
+          exit 0
 
       - name: Delete cluster
         run: kind delete cluster
